Repository kowainik/hit-on, pull requests merged in 2020-02, with the labels that each got.

#140 [#110] Increase width for file names
  src/Hit/Git/Status.hs
Labels: Git

#143 [#142] Implement prettier 'hit log' command
  src/Hit/Git/Log.hs
Labels: Git

#141 [#15] When new branch for issue created add the user as assignee
  CHANGELOG.md
  src/Hit/Git/New.hs
  src/Hit/Issue.hs
Labels: CLI, GitHub, enhancement

#145 Use colourista
  CHANGELOG.md
  hit-on.cabal
  src/Hit/Cli.hs
  src/Hit/ColorTerminal.hs
  src/Hit/Git/Clear.hs
  src/Hit/Git/Clone.hs
  src/Hit/Git/Commit.hs
  src/Hit/Git/Common.hs
  src/Hit/Git/Current.hs
  src/Hit/Git/New.hs
  src/Hit/Git/Status.hs
  src/Hit/Issue.hs
  src/Hit/Prompt.hs
  stack.yaml
Labels: beauty, library, refactoring

#147 Drop nix support
  .github/workflows/ci.yml
  README.md
  default.nix
Labels: CI
